name = "qq-music-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "qq-music-api"
database_id = "0eb000e7-4400-4d59-b087-96a5d777e92e" 

# 定时刷新凭证 (每小时)
[triggers]
crons = ["0 * * * *"]


# 开启日志
[observability]
[observability.logs]
enabled = true
invocation_logs = true